apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunarr-deployment
  namespace: media
  labels:
    app: tunarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunarr
  template:
    metadata:
      labels:
        app: tunarr
    spec:
      containers:
      - name: tunarr
        image: chrisbenincasa/tunarr:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: "/tunarr"
          name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tunarrfinconfig-pvc
