annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update image to 3.0.10.1567
apiVersion: v2
appVersion: 3.0.10.1567
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: Smart PVR for newsgroup and bittorrent users
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/sonarr
icon: https://github.com/Sonarr/Sonarr/blob/phantom-develop/Logo/512.png?raw=true
keywords:
- sonarr
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: admin@aste.tools
  name: k8s-home-lab
name: sonarr
sources:
- https://github.com/Sonarr/Sonarr
- https://github.com/onedr0p/containers
version: 17.1.1
