apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-ingress-cert
  namespace: istio-gateway
spec:
  dnsNames:
    - prometheus.greaterfaydark.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: prometheus-ingress-lets-encrypt
  usages:
    - digital signature
    - key encipherment
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ingress-cert
  namespace: istio-gateway
spec:
  dnsNames:
    - grafana.greaterfaydark.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: grafana-ingress-lets-encrypt
  usages:
    - digital signature
    - key encipherment
