apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: prometheus-operator
spec:
  gateways:
    - prometheus-gateway
  hosts:
    - 'prometheus.greaterfaydark.net'
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus-operated.prometheus-operator.svc.cluster.local
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: prometheus-operator
spec:
  gateways:
    - prometheus-gateway
  hosts:
    - 'grafana.greaterfaydark.net'
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kube-prometheus-grafana.prometheus-operator.svc.cluster.local
